### PR TITLE
GSREN3D-355 - first version of enedis api

### PR DESCRIPTION
**Pull request by toni-garcia-camptocamp**
GSREN3D-355 - first version of enedis api

https://jira.camptocamp.com/browse/GSREN3D-355

.env need to be create to test 
Documentation enedis API: https://datahub-enedis.fr/services-api/data-connect/ressources/decouvrir/

### CODE REVIEW

**Comment by toni-garcia-camptocamp** [comment]
@MaYohann 
If you have the rights can you add Anais to this repo please

**Comment by toni-garcia-camptocamp** [comment]
@ismailsunni  @MaYohann 
I have store the data (prm, state) into session 
To access of enedis api we need the generation of a token. This token can be use during 3 hours and half. I think the best usage is to generate one token and use it for all users . But the storage in session is for one user only. Maybe we can add a sql_lite db to store the token , what do you think ? 

In this first api i generate a new token (1 token by user) on every call of the function getAnnualConsumption

**Comment by ismailsunni** [comment]
hi @toni-garcia-camptocamp 
could you put a small readme on how to run/test it?

**Comment by ismailsunni** [comment]
Hi @toni-garcia-camptocamp 
I got this error when I ran `node run dev`. Any idea why? I have run `npm i` and update the .env file

```
/home/isunni/dev/js/cooperation_jn_backend/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/services/api-enedis.ts:41:34 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(config: AxiosRequestConfig<any>): AxiosPromise<any>', gave the following error.
    Argument of type '{ method: string; url: string; headers: { 'Content-Type': string; }; data: string; }' is not assignable to parameter of type 'AxiosRequestConfig<any>'.
      Types of property 'method' are incompatible.
        Type 'string' is not assignable to type 'Method | undefined'.
  Overload 2 of 2, '(url: string, config?: AxiosRequestConfig<any> | undefined): AxiosPromise<any>', gave the following error.
    Argument of type '{ method: string; url: string; headers: { 'Content-Type': string; }; data: string; }' is not assignable to parameter of type 'string'.

41     const response = await axios(config)
                                    ~~~~~~

src/services/api-enedis.ts:54:34 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(config: AxiosRequestConfig<any>): AxiosPromise<any>', gave the following error.
    Argument of type '{ method: string; url: string; headers: { Authorization: string; accept: string; }; }' is not assignable to parameter of type 'AxiosRequestConfig<any>'.
      Types of property 'method' are incompatible.
        Type 'string' is not assignable to type 'Method | undefined'.
  Overload 2 of 2, '(url: string, config?: AxiosRequestConfig<any> | undefined): AxiosPromise<any>', gave the following error.
    Argument of type '{ method: string; url: string; headers: { Authorization: string; accept: string; }; }' is not assignable to parameter of type 'string'.

54     const response = await axios(config)
                                    ~~~~~~


    at createTSError (/home/isunni/dev/js/cooperation_jn_backend/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/home/isunni/dev/js/cooperation_jn_backend/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/home/isunni/dev/js/cooperation_jn_backend/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/home/isunni/dev/js/cooperation_jn_backend/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/home/isunni/dev/js/cooperation_jn_backend/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Object.require.extensions.<computed> [as .ts] (/home/isunni/dev/js/cooperation_jn_backend/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19) {
  diagnosticCodes: [ 2769, 2769 ]
}
[nodemon] app crashed - waiting for file changes before starting...
```

**Pull request merged**
